Sentry.Xamarin.Forms/Internals/NativeEventProcessor.droid.cs
Sentry.Xamarin.Forms/Internals/NativeEventProcessor.ios.cs
Sentry.Xamarin.Forms/Internals/NativeEventProcessor.uwp.cs
Sentry.Xamarin.Forms/Internals/NativeIntegration.droid.cs
Sentry.Xamarin.Forms/Internals/XamarinFormsEventProcessor.cs
Sentry.Xamarin.Forms/SentryXamarinFormsIntegration.cs
Tests/Sentry.Xamarin.Forms.Tests.UWP/Internals/NativeIntegrationTests.cs
Tests/Sentry.Xamarin.Forms.Tests.UWP/Sentry.Xamarin.Forms.Tests.UWP.csproj
Tests/Sentry.Xamarin.Forms.Tests.UWP/SentryXamarinFormsIntegrationTests.cs

I Also refactored SentryXamarinFormsIntegration to allow more testing.
Closes #22.
The release format is: 
iOS: "{app packagename}"@{app number}"
Android: "{app packagename}"@{app number}"
UWP: "{app GUID}"@{app number}"

feat: Add Release project@version if release is not set.

---

Sentry.Xamarin.Forms/Internals/XamarinFormsEventProcessor.cs

I forgot to remove the ToUpper...
https://sentry.io/organizations/sentry-sdks/issues/2096393321/events/08f4d92c9c3243e4b16b591b5d658ec6/
proof it got fixed.

ref: Remove the ToUpper on platform

---

README.md
Samples/Sample.Xamarin.Core/Helpers/SentryInitializer.cs
Samples/Sample.Xamarin.UWP/App.xaml.cs
Sentry.Xamarin.Forms/Extensions/SentryOptionsExtensions.cs
Sentry.Xamarin.Forms/Extensions/SentryXamarinFormsIntegrationExtensions.cs
Sentry.Xamarin.Forms/Extensions/SentryXamarinOptionsExtensions.cs
Sentry.Xamarin.Forms/Internals/NativeIntegration.uwp.cs
Sentry.Xamarin.Forms/Internals/SentryXamarinOptions.cs
Sentry.Xamarin.Forms/SentryXamarin.cs
Sentry.Xamarin.Forms/SentryXamarinFormsIntegration.cs
Sentry.Xamarin.Forms/SentryXamarinOptions.cs
Tests/Sentry.Xamarin.Forms.Testing/Sentry.Xamarin.Forms.Testing.csproj
Tests/Sentry.Xamarin.Forms.Tests.UWP/Extensions/SentryOptionsExtensionsTests.cs
Tests/Sentry.Xamarin.Forms.Tests.UWP/Extensions/SentryXamarinOptionsExtensionsTests.cs
Tests/Sentry.Xamarin.Forms.Tests.UWP/Sentry.Xamarin.Forms.Tests.UWP.csproj
Tests/Sentry.Xamarin.Forms.Tests.UWP/SentryXamarinFormsIntegrationTests.cs

- Created API Initializer.
- moved some code from SentryXamarinFormsIntegration to SentryXamarin and SentryOptionsExtensions.
- Automatically Set the Cache Directory path once initialized.
- Add Extension for disabling the Automatic Cache Folder setter.
- Updated tests.
Initialization changes:
Before:
```
SentrySdk.Init(o =>
{
o.Dsn = "https://5a193123a9b841bc8d8e42531e7242a1@o447951.ingest.sentry.io/5560112";
o.CacheDirectoryPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
o.AddIntegration(new SentryXamarinFormsIntegration());
});
```
After:
```
SentryXamarin.Init(options =>
{
options.Dsn = "https://5a193123a9b841bc8d8e42531e7242a1@o447951.ingest.sentry.io/5560112";
});
```
Operations like WithScope, ConfigureScope, CaptureMessage weren't changed so the …

ref: Initializer refactory

---

Samples/Sample.Xamarin.Core/Extensions/SentryIdExtensions.cs
Samples/Sample.Xamarin.Core/Sample.Xamarin.Core.csproj
Samples/Sample.Xamarin.Droid/Sample.Xamarin.Droid.csproj
Samples/Sample.Xamarin.iOS/Sample.Xamarin.iOS.csproj
Sentry.Xamarin.Forms/Sentry.Xamarin.Forms.csproj
Tests/Sentry.Xamarin.Forms.Tests.UWP/Internals/NativeIntegrationTests.cs

- min version is 3.0.0 Alpha 8 (there were some breaking changes between version 6 and 8)
-  Fixed tests for .NET Native.

ref: Bump SentrySDK version and fixed test for .NET Native

---

Directory.Build.props
Samples/Sample.Xamarin.Core/Sample.Xamarin.Core.csproj
Samples/Sample.Xamarin.Droid/Sample.Xamarin.Droid.csproj
Samples/Sample.Xamarin.iOS/Sample.Xamarin.iOS.csproj

Sentry.NET SDK Alpha 9 -> 10
Increased SDK version from Alpha 3 to Alpha 4.

ref: update version of sentry SDK and Xamarin Forms SDK version.

---

Directory.Build.props
Src/Sentry.Xamarin/Internals/DeviceModel.ios.cs
Src/Sentry.Xamarin/Internals/NativeEventProcessor.uwp.cs
Src/Sentry.Xamarin/Internals/NativeIntegration.ios.cs
Src/Sentry.Xamarin/Internals/NativeIntegration.uwp.cs

Sentry .NET SDK 3.0.1 breaks the release 1.0.0 so I'm updating the SDK to be compatible with it.

Ref: Update Sentry .NET SDK and fixed conflicts.

---

CHANGELOG.md
Directory.Build.props

With that, Sentry.Xamarin will get additional features like when the app was started and the device boot time.

Update Sentry.NET to 3.3.0

---

CHANGELOG.md
Src/Sentry.Xamarin/Internals/XamarinEventProcessor.cs

I noticed weird data during dogfooding and it seems like the Xamarin Essentials Manufacture data is the expected data for the field device brand.
the proposed fix is just to set the DeviceInfo.Manufacturer parameter as a device.Brand.
event 4811c4c8 got the fixed applied while ...841 is the current state of this SDK.
a sample picture of an event revealing the brand being set to the wrong parameter.

Fix: Device brand set on device manufacture  

---

CHANGELOG.md
Directory.Build.props
Src/Sentry.Xamarin/Sentry.Xamarin.csproj
Src/Sentry.Xamarin/SentryXamarinOptions.cs

The following PR includes.
* Sentry SDK version increased to 3.5.0
* IsEnvironmentUserDisabled by  default 
* Fix https://github.com/getsentry/sentry-dotnet/issues/931 and https://github.com/getsentry/sentry-xamarin/issues/72 by adding the correct NuGet package references.

fix IsEnvironmentUser disabled by default and Json issue on iOS

---

CHANGELOG.md
Src/Sentry.Xamarin/Extensions/IHubExtensions.cs
Tests/Sentry.Xamarin.Forms.UWP.Tests/Extensions/SentryXamarinOptionsExtensionsTests.cs
Tests/Sentry.Xamarin.Forms.UWP.Tests/Internals/XamarinEventProcessorTests.cs
Tests/Sentry.Xamarin.Tests/Extensions/IHubExtensionsTests.cs

Fix null data on breadcrumb.

---

.github/workflows/build.yaml
Samples/Sample.Xamarin.Core/Sample.Xamarin.Core.csproj
Samples/Sample.Xamarin.Droid/Sample.Xamarin.Droid.csproj
Samples/Sample.Xamarin.UWP/Sample.Xamarin.UWP.csproj
Samples/Sample.Xamarin.iOS/Dependencies/NativeCrash.cs
Samples/Sample.Xamarin.iOS/Main.cs
Samples/Sample.Xamarin.iOS/Sample.Xamarin.iOS.csproj

NuGet Restore now throws an error on macOS when trying to restore a UWP project, the previous behavior was UWP projects were ignored on macOS.
MSBuild will do the same operation but ignore the UWP platform on  macOS.
#skip-changelog.

Fix break change with new MacOS image

---

CHANGELOG.md
Src/Sentry.Xamarin/Extensions/SentryXamarinOptionsExtensions.cs
Src/Sentry.Xamarin/Internals/Device/Screenshot/ScreenshotAttachmentContent.cs

- The new behavior will drop the screenshot in case of a failure instead of creating an empty screenshot.
Fixes #86

Fix 0 byte screenshot being sent to Sentry

---

README.md
Src/Directory.Build.props

This PR does the following:
- Includes the readme file in the nuget package, like we do already for sentry-dotnet.  This will let it be visible at https://www.nuget.org/packages/Sentry.Xamarin/ instead of just the description text. (on next publish)
- Removes all HTML from the readme, as nuget won't render HTML
- Switches to the purple Sentry logo, which is readable on both white and black backgrounds
See also #116 & #117.
#skip-changelog

Update readme and include in nuget package

---

CHANGELOG.md
Samples/Sample.Xamarin.Droid/MainActivity.cs
Src/Sentry.Xamarin/Extensions/SentryXamarinOptionsExtensions.cs
Tests/Sentry.Xamarin.Tests/Extensions/SentryXamarinOptionsExtensionsTests.cs
Tests/Sentry.Xamarin.Tests/Sentry.Xamarin.Tests.csproj

This additional step alters the current  DSN  on Android if ran on Saas to use the alternative URL in order to communicate with the server to avoid https://github.com/mono/mono/issues/21233
Fixes #107

adjust DSN for Android.

---

CHANGELOG.md
Directory.Build.props

The bump includes an important fix that fixes the unobservable exceptions found on #115.
Close #115

Bump Sentry .NET 3.17.1

---

.github/workflows/add-platform-label.yml
.github/workflows/build.yaml
.github/workflows/danger.yml
.github/workflows/release.yml

- Update all GitHub actions to their current versions
- Add a comment about why we need to stay on `windows-2019`
- `windows-latest` doesn't have the older Windows SDK version we're targeting
- Use `startsWith` in conditional tests, to reduce number of places to update in the future
- Remove the manual install of .NET 5.  We'll use the pre-installed version from the virtual environment.
- Note, that we were installing 5.0.100, which is quite old now.  Among other things, that was preventing the readme file from actually make it into the `<readme>` tag in the generated .nuspec file within the nuget package, as `<PackageReadmeFile>` tooling was added in 5.0.300.
#skip-changelog

chore: Update Github Actions

---

CHANGELOG.md
Directory.Build.props

In part due to https://github.com/getsentry/sentry-dotnet/issues/1963

Update Sentry to 3.22.0

---

CHANGELOG.md
Directory.Build.props

In part due to https://github.com/getsentry/sentry-dotnet/pull/2026

Update Sentry to 3.23.1

---

CHANGELOG.md
Src/Sentry.Xamarin/SentryXamarin.cs

Fixes #129 by automatically preventing multiple initialization.  Writes a message to stderr accordingly.
Will continue pursuing a fix for the root cause in https://github.com/getsentry/sentry-dotnet/issues/2033.

Avoid repeat initialization

---

CHANGELOG.md
Directory.Build.props

This PR bumps Sentry .NET SDK to version 3.26.2

Bump Sentry dotnet 3.26.2

---

CHANGELOG.md
Directory.Build.props
README.md
Src/Sentry.Xamarin.Forms/Sentry.Xamarin.Forms.csproj
Src/Sentry.Xamarin/Internals/SentryAndroidHelpers.droid.cs
Src/Sentry.Xamarin/Sentry.Xamarin.csproj
Src/Sentry.Xamarin/SentryXamarinOptions.cs

- Updates Sentry to 3.27.0
- Adds the `Sentry.AndroidAssemblyReader` as a dependency for Android targets, allowing symbolication of line numbers on Android.  Resolves #134

Update Sentry.NET SDK to 3.27.0 and support symbolication on Android

---

CHANGELOG.md
Src/Sentry.Xamarin/Sentry.Xamarin.csproj

Fixes issue with Sentry CLI MSBuild Integration for Xamarin

Update Sentry to 3.27.1

---

.github/workflows/build.yaml
.github/workflows/release.yml
CHANGELOG.md
README.md
Src/Sentry.Xamarin/Internals/Device/Screenshot/ScreenshotAttachment.cs
Src/Sentry.Xamarin/Sentry.Xamarin.csproj
Tests/Sentry.Xamarin.Forms.Testing/Mock/MockHub.cs

- fixed break changes.
- bumped android API to 30 due to new Google requirements.
-  bump Sentry .NET to 4.0.3
- fixed github workflow build that broke with the API increase.

Bump Sentry.NET 4.0.3

---

CHANGELOG.md
Samples/Sample.Xamarin.Droid/Sample.Xamarin.Droid.csproj
Samples/Sample.Xamarin.iOS/Sample.Xamarin.iOS.csproj
Src/Sentry.Xamarin/Sentry.Xamarin.csproj
Tests/Sentry.Xamarin.Forms.Testing/Mock/MockHub.cs

This PR bumps Sentry .NET to version 4.5.0.
No break changes were seen.

Bump Sentry .NET 4.5.0
